version: "3"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "23798:${DB_PORT}"
    env_file: ./envs/.env.init
  indexer-init:
    build: 
      context: .
      dockerfile: ./Dockerfile 
    restart: on-failure
    depends_on: 
      - db
    env_file: ./envs/.env.init
  indexer-sepolia:
    build: 
      context: .
      dockerfile: ./Dockerfile 
    restart: on-failure
    depends_on: 
      - indexer-init
    env_file: ./envs/.env.sepolia
  indexer-holesky:
    build: 
      context: .
      dockerfile: ./Dockerfile 
    restart: on-failure
    depends_on: 
      - indexer-init
    env_file: ./envs/.env.holesky
  api:
    build: 
      context: .
      dockerfile: ./Dockerfile.api
    env_file: ./envs/.env.init
    ports:
      - "8000:8000"
