name: Testnet Squid Indexer

on:
  release:
    types:
      - published

run-name: Deploy Squid-Indexer to Testnet - ${{ inputs.release_tag }} by @${{ github.actor }}

env:
  ENVIRONMENT: TESTNET
  REGISTRY: 'ghcr.io'
  TAG: 'latest'
  VERSION: ${{ github.event.release.tag_name }}

jobs:
  push:
    name: push
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      packages: write
      actions: read

    steps:
      - name: checkout the source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: login to ghcr
        id: ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build / tag / push docker image into ghcr
        id: build-and-push-tag
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.VERSION }},${{ env.REGISTRY }}/${{ github.repository }}:${{ github.ref_name }}

      - name: slack notify
        uses: 8398a7/action-slack@v3
        with:
            status: ${{ job.status }}
            fields: repo,message,commit,author,action,job,eventName,ref,workflow 
        env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 
        if: always()

  deploy:
   needs: push
   name: deploy
   runs-on: ubuntu-latest
   environment: testnet
   permissions:
     contents: read
     id-token: write
     actions: write
   env:
     AWS_REGION: '${{ secrets.AWS_REGION }}'
     AWS_TESTNET: '${{ secrets.AWS_TESTNET }}'
   steps:
     - name: checkout ecs repo
       uses: actions/checkout@v4
       with:
         repository: sprintertech/devops
         token: ${{ secrets.GHCR_TOKEN }}
         ref: main

     - name: render jinja2 templates to task definition json files
       uses: cuchi/jinja2-action@v1.2.0
       with:
         template: 'squid-indexer/ecs/task_definition-squid-indexer-${{ env.ENVIRONMENT }}.j2'
         output_file: 'squid-indexer/ecs/task_definition-squid-indexer-${{ env.ENVIRONMENT }}.json'
         data_format: json
         variables: |
           awsAccountId=${{ env.AWS_TESTNET }}
           awsRegion=${{ env.AWS_REGION }}
           awsEnv=${{ env.ENVIRONMENT }}
           imageTag=${{ env.VERSION }}

     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
         role-to-assume: arn:aws:iam::${{ env.AWS_TESTNET }}:role/github-actions-${{ env.ENVIRONMENT }}-chainbridge
         aws-region: ${{ env.AWS_REGION }}
         role-session-name: GithubActions

     - name: Deploy to Amazon ECS
       uses: aws-actions/amazon-ecs-deploy-task-definition@v1
       with:
         task-definition: squid-indexer/ecs/task_definition-squid-indexer-${{ env.ENVIRONMENT }}.json
         service: squid-indexer-service-${{ env.ENVIRONMENT }}
         cluster: explorer-indexer-${{ env.ENVIRONMENT }}
         wait-for-service-stability: true

     - name: slack notify
       uses: 8398a7/action-slack@v3
       with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,job,eventName,ref,workflow # selectable (default: repo,message)
       env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
       if: always()
       