name: E2E Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run Docker
        run: docker compose up --build
      - name: Wait
        run: sleep 81s
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn run test:e2e
      - name: Setup tmate session
        if: success() || failure()
        uses: mxschmitt/action-tmate@v3
      - name: Clean up Docker containers
        if: always()
        run: docker compose down